[package]
name = "libm"
version = "0.2.15"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
description = "libm in pure Rust"
categories = ["no-std"]
keywords = ["libm", "math"]
repository = "https://github.com/rust-lang/compiler-builtins"
license = "MIT"
edition = "2021"
rust-version = "1.63"

[features]
default = ["arch"]

# certifiable parts of libm
sonair_certified = []

# Enable architecture-specific features such as SIMD or assembly routines.
arch = []

# Make some internal things public for testing.
unstable-public-internals = []
# Used to prevent using any intrinsics or arch-specific code.
#
# HACK: this is a negative feature which is generally a bad idea in Cargo, but
# we need it to be able to forbid other features when this crate is used in
# Rust dependencies. Setting this overrides all features that may enable
# hard float operations.
force-soft-floats = []

[dev-dependencies]
no-panic = "0.1.35"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  # compiler-builtins sets this feature, but we use it in `libm`
  'cfg(feature, values("compiler-builtins"))',
] }
